name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade uv

      - name: Create and activate virtual environment
        run: |
          uv venv
          source .venv/bin/activate

      - name: Install build dependencies
        run: |
          uv add setuptools-scm

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI
        run: |
          uv publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
