name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Download NLTK resources
        run: |
          mkdir -p ~/nltk_data
          chmod -R 777 ~/nltk_data

          python -c "import nltk; nltk.download('punkt', download_dir='~/nltk_data'); nltk.download('wordnet', download_dir='~/nltk_data'); nltk.download('stopwords', download_dir='~/nltk_data')"

          python -c "import nltk; nltk.data.path.append('~/nltk_data'); print('NLTK resources found:', nltk.data.path)"

      - name: Run tests
        run: pytest
